import os
import json
from pathlib import Path

# Import loader and concurrent engine
import sys, os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))
from load_bollinger_strategies import load_bollinger_strategies
from backtest.concurrent_engine import ConcurrentBacktestEngine


def main():
    # Define the 8 pairs configuration (M15 timeframe)
    pairs_config = [
        {"symbol": "GOLD",   "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
        {"symbol": "SILVER", "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
        {"symbol": "EURUSD", "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
        {"symbol": "GBPUSD", "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
        {"symbol": "USDJPY", "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
        {"symbol": "USDCHF", "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
        {"symbol": "AUDUSD", "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
        {"symbol": "NZDUSD", "timeframe": 15, "tf_name": "M15", "tier": "ST4"},
    ]

    # Load all Bollinger strategy instances for the whitelist
    whitelist = load_bollinger_strategies(pairs_config)

    # Initialise the concurrent backtest engine with global risk limits
    engine = ConcurrentBacktestEngine(
        whitelist=whitelist,
        max_positions=3,            # global max open positions
        max_per_symbol=2,          # max open per symbol
        max_lot_per_position=0.02, # fixed lot size per position
    )

    # Run the backtest – returns a dict with aggregated statistics
    results = engine.run_backtest()

    # Extract key metrics for verification
    pf = results.get("profit_factor", 0)
    dd = results.get("max_drawdown_pct", 100)
    position_violations = results.get("position_limit_violations", [])

    # Build a markdown report
    report_lines = []
    report_lines.append("# Concurrent Bollinger 8‑Pair Backtest Report")
    report_lines.append("")
    report_lines.append(f"**Date:** {Path(__file__).parent.parent.name}")
    report_lines.append("")
    report_lines.append("## Summary")
    report_lines.append(f"- **Total PnL:** {results.get('total_pnl', 0):.2f} USD")
    report_lines.append(f"- **Profit Factor (PF):** {pf:.2f}")
    report_lines.append(f"- **Maximum Drawdown (DD%):** {dd:.2f}%")
    report_lines.append("")
    report_lines.append("## Position Limits Check")
    if not position_violations:
        report_lines.append("- No violations: portfolio respected max 3 open positions, max 2 per symbol, and lot‑size caps.")
    else:
        report_lines.append("- **Violations detected:**")
        for v in position_violations:
            report_lines.append(f"  - {v}")
    report_lines.append("")
    report_lines.append("## Detailed Strategy Results")
    for strat in results.get('strategies', []):
        report_lines.append(f"- **{strat.get('strategy_id', 'Unnamed')}** – PnL: {strat.get('pnl',0):.2f}, Trades: {strat.get('trades',0)}")
    report_lines.append("---")
    report_lines.append("*Generated by `run_concurrent_bollinger_8pairs.py`*")

    # Write report to the project reports folder
    report_path = Path(__file__).parents[2] / "reports" / "concurrent_portfolio_backtest_report.md"
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text("\n".join(report_lines))

    # Console output for quick glance
    print("Backtest completed.")
    print(f"Profit Factor: {pf:.2f}, Max DD%: {dd:.2f}%")
    if position_violations:
        print("Position limit violations encountered!")
    else:
        print("All position limits respected.")


if __name__ == "__main__":
    main()
