import pandas as pd
df = pd.read_csv('backtest_results/v7_multiindex_trades.csv')

print('=== FINE-TUNED AGGRESSIVE RESULTS ===')
print(f"Total Trades: {len(df)}")
print(f"Total PnL: Rs.{df.pnl_rs.sum():,.0f}")
print(f"Win Rate: {df.won.sum()/len(df)*100:.1f}%")
print(f"Avg per trade: Rs.{df.pnl_rs.mean():.0f}")
print()
print('--- PER INDEX ---')
print(df.groupby('index')['pnl_rs'].agg(['count','sum']).round(0))
print()
print('--- DAILY METRICS ---')
daily = df.groupby('date')['pnl_rs'].sum()
print(f"Best Day: Rs.{daily.max():,.0f}")
print(f"Avg Day: Rs.{daily.mean():.0f}")
print(f"Days >5000: {(daily > 5000).sum()}/{(daily > 0).sum()}")
print(f"Days >10000: {(daily > 10000).sum()}")
print()
print('--- CAPITAL RETURNS (5L) ---')
total = df.pnl_rs.sum()
capital = 500000
print(f"Total Return: {total/capital*100:.1f}%")
print(f"Daily Avg: {daily.mean()/capital*100:.2f}%")
print(f"Best Day %: {daily.max()/capital*100:.1f}%")
